coverage:
  precision: 2
  round: down          
  range: 50...100

    patch:                     
      default:
        enabled: yes
        target: 80%
        threshold: 5%          
        
comment: false


